# Generated by Django 3.0.7 on 2020-06-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membership_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='membership',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
