# Generated by Django 3.0.7 on 2020-06-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_auto_20200621_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.TextField(default='DESCRIPTION'),
        ),
    ]
