# Generated by Django 3.0.7 on 2020-06-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_auto_20200621_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='plan_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
