# Generated by Django 3.0.7 on 2020-06-25 22:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_auto_20200625_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='country',
            field=django_countries.fields.CountryField(default='Ireland', max_length=2),
        ),
    ]
