# Generated by Django 3.0.7 on 2020-06-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_auto_20200626_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='description',
            new_name='description_five',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='image',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='image_url',
        ),
        migrations.AddField(
            model_name='membership',
            name='description_four',
            field=models.TextField(default='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='membership',
            name='description_one',
            field=models.TextField(default='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='membership',
            name='description_three',
            field=models.TextField(default='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='membership',
            name='description_two',
            field=models.TextField(default='DESCRIPTION'),
        ),
    ]
