# Generated by Django 3.0.7 on 2020-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0012_auto_20200627_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='description_four',
            field=models.TextField(default='DESCRIPTION', max_length=500),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description_one',
            field=models.TextField(default='DESCRIPTION', max_length=500),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description_three',
            field=models.TextField(default='DESCRIPTION', max_length=500),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description_two',
            field=models.TextField(default='DESCRIPTION', max_length=500),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Regular', 'reg'), ('Premium', 'prem'), ('Free', 'free')], default='Free', max_length=200),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='full_name',
            field=models.CharField(default='Please enter your full name', max_length=200),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='phone_number',
            field=models.CharField(default='Please enter your phone number', max_length=30),
        ),
    ]
