# Generated by Django 3.0.7 on 2020-06-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0015_auto_20200628_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='postcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
