# Generated by Django 3.0.7 on 2020-06-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0016_auto_20200628_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='description_four',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description_one',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description_three',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description_two',
            field=models.TextField(),
        ),
    ]
