# Generated by Django 3.0.7 on 2020-06-29 12:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0017_auto_20200628_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='country',
            field=django_countries.fields.CountryField(default='uk', max_length=4),
            preserve_default=False,
        ),
    ]
