# Generated by Django 3.0.7 on 2020-06-29 12:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0018_auto_20200629_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='country',
            field=django_countries.fields.CountryField(max_length=4),
        ),
    ]
