# Generated by Django 3.0.7 on 2020-06-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0020_auto_20200629_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='country',
        ),
    ]
