# Generated by Django 3.0.7 on 2020-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_currentitem_shortdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentitem',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
